// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
  [KeyType in keyof T]: T[KeyType];
};
/** Content for Gestion locative documents */
interface GestionLocativeDocumentData {
  /**
   * Slice Zone field in *Gestion locative*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: gestion_locative.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismicT.SliceZone<GestionLocativeDocumentDataSlicesSlice>;
}
/**
 * Slice for *Gestion locative → Slice Zone*
 *
 */
type GestionLocativeDocumentDataSlicesSlice =
  | OverviewSlice
  | StrengthsSlice
  | ContactBlockSlice;
/**
 * Gestion locative document from Prismic
 *
 * - **API ID**: `gestion_locative`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GestionLocativeDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithoutUID<
    Simplify<GestionLocativeDocumentData>,
    "gestion_locative",
    Lang
  >;
export type AllDocumentTypes = GestionLocativeDocument;
/**
 * Primary content in ContactBlock → Primary
 *
 */
interface ContactBlockSliceDefaultPrimary {
  /**
   * title field in *ContactBlock → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_block.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
  /**
   * description field in *ContactBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_block.primary.description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismicT.RichTextField;
  /**
   * action field in *ContactBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_block.primary.action
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  action: prismicT.RichTextField;
  /**
   * illustration field in *ContactBlock → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_block.primary.illustration
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  illustration: prismicT.ImageField<never>;
}
/**
 * Default variation for ContactBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ContactBlockSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Simplify<ContactBlockSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *ContactBlock*
 *
 */
type ContactBlockSliceVariation = ContactBlockSliceDefault;
/**
 * ContactBlock Shared Slice
 *
 * - **API ID**: `contact_block`
 * - **Description**: `ContactBlock`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ContactBlockSlice = prismicT.SharedSlice<
  "contact_block",
  ContactBlockSliceVariation
>;
/**
 * Primary content in IllustratedContent → Primary
 *
 */
interface OverviewSliceDefaultPrimary {
  /**
   * title field in *IllustratedContent → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: overview.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
  /**
   * text field in *IllustratedContent → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: overview.primary.text
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  text: prismicT.RichTextField;
  /**
   * illustration field in *IllustratedContent → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: overview.primary.illustration
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  illustration: prismicT.ImageField<never>;
}
/**
 * Default variation for IllustratedContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type OverviewSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Simplify<OverviewSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *IllustratedContent*
 *
 */
type OverviewSliceVariation = OverviewSliceDefault;
/**
 * IllustratedContent Shared Slice
 *
 * - **API ID**: `overview`
 * - **Description**: `Overview`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type OverviewSlice = prismicT.SharedSlice<
  "overview",
  OverviewSliceVariation
>;
/**
 * Primary content in PricingTier → Primary
 *
 */
interface PricingTierSliceDefaultPrimary {
  /**
   * name field in *PricingTier → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing_tier.primary.name
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  name: prismicT.KeyTextField;
  /**
   * tagline field in *PricingTier → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing_tier.primary.tagline
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  tagline: prismicT.KeyTextField;
  /**
   * description field in *PricingTier → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing_tier.primary.description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismicT.RichTextField;
  /**
   * illustration field in *PricingTier → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing_tier.primary.illustration
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  illustration: prismicT.ImageField<never>;
  /**
   * recommended field in *PricingTier → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: pricing_tier.primary.recommended
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  recommended: prismicT.BooleanField;
}
/**
 * Default variation for PricingTier Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type PricingTierSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Simplify<PricingTierSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *PricingTier*
 *
 */
type PricingTierSliceVariation = PricingTierSliceDefault;
/**
 * PricingTier Shared Slice
 *
 * - **API ID**: `pricing_tier`
 * - **Description**: `PricingTier`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type PricingTierSlice = prismicT.SharedSlice<
  "pricing_tier",
  PricingTierSliceVariation
>;
/**
 * Item in Strengths → Items
 *
 */
export interface StrengthsSliceDefaultItem {
  /**
   * icon field in *Strengths → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: strengths.items[].icon
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  icon: prismicT.ImageField<never>;
  /**
   * title field in *Strengths → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: strengths.items[].title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
  /**
   * description field in *Strengths → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: strengths.items[].description
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  description: prismicT.KeyTextField;
}
/**
 * Default variation for Strengths Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type StrengthsSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<StrengthsSliceDefaultItem>
>;
/**
 * Slice variation for *Strengths*
 *
 */
type StrengthsSliceVariation = StrengthsSliceDefault;
/**
 * Strengths Shared Slice
 *
 * - **API ID**: `strengths`
 * - **Description**: `Strengths`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type StrengthsSlice = prismicT.SharedSlice<
  "strengths",
  StrengthsSliceVariation
>;
declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }
  namespace Content {
    export type {
      GestionLocativeDocumentData,
      GestionLocativeDocumentDataSlicesSlice,
      GestionLocativeDocument,
      AllDocumentTypes,
      ContactBlockSliceDefaultPrimary,
      ContactBlockSliceDefault,
      ContactBlockSliceVariation,
      ContactBlockSlice,
      OverviewSliceDefaultPrimary,
      OverviewSliceDefault,
      OverviewSliceVariation,
      OverviewSlice,
      PricingTierSliceDefaultPrimary,
      PricingTierSliceDefault,
      PricingTierSliceVariation,
      PricingTierSlice,
      StrengthsSliceDefaultItem,
      StrengthsSliceDefault,
      StrengthsSliceVariation,
      StrengthsSlice,
    };
  }
}
