// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  contact_block: dynamic(() => import("./ContactBlock")),
  offers: dynamic(() => import("./Offers")),
  overview: dynamic(() => import("./IllustratedContent")),
  pricing_tier: dynamic(() => import("./PricingTier")),
  strengths: dynamic(() => import("./Strengths")),
};
