// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  contact_block: dynamic(() => import("./ContactBlock")),
  offers: dynamic(() => import("./Offers")),
  offers_compare: dynamic(() => import("./OffersCompare")),
  overview: dynamic(() => import("./IllustratedContent")),
  projects: dynamic(() => import("./Projects")),
  strengths: dynamic(() => import("./Strengths")),
};
